-- =============================================================
-- StockFlow - Script de configuração completa do banco de dados
-- =============================================================

CREATE DATABASE IF NOT EXISTS stockflow
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE stockflow;

SET FOREIGN_KEY_CHECKS = 0;

-- -------------------------------------------------------------
-- 1. localizacao
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS localizacao (
  id           INT            NOT NULL AUTO_INCREMENT,
  corredor     VARCHAR(10)    NOT NULL,
  nivel        INT            NOT NULL,
  posicao      INT            NOT NULL,
  descricao    VARCHAR(255)   NULL,
  criado_em    DATETIME       NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -------------------------------------------------------------
-- 2. produto
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS produto (
  id               INT            NOT NULL AUTO_INCREMENT,
  nome             VARCHAR(255)   NOT NULL,
  categoria        VARCHAR(100)   NOT NULL,
  descricao        TEXT           NULL,
  unidade_medida   VARCHAR(20)    NOT NULL,
  estoque_minimo   DECIMAL(10,3)  NOT NULL DEFAULT 0,
  ativo            TINYINT(1)     NOT NULL DEFAULT 1,
  criado_em        DATETIME       NOT NULL DEFAULT NOW(),
  atualizado_em    DATETIME       NOT NULL DEFAULT NOW() ON UPDATE NOW(),
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -------------------------------------------------------------
-- 3. usuario
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS usuario (
  id          INT          NOT NULL AUTO_INCREMENT,
  nome        VARCHAR(255) NOT NULL,
  email       VARCHAR(255) NOT NULL UNIQUE,
  senha_hash  VARCHAR(255) NOT NULL,
  perfil      ENUM('administrador','operador') NOT NULL DEFAULT 'operador',
  ativo       TINYINT(1)   NOT NULL DEFAULT 1,
  criado_em   DATETIME     NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -------------------------------------------------------------
-- 4. lote
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS lote (
  id               INT            NOT NULL AUTO_INCREMENT,
  numero_lote      VARCHAR(100)   NOT NULL UNIQUE,
  data_fabricacao  DATETIME       NOT NULL DEFAULT NOW(),
  data_validade    DATETIME       NULL,
  quantidade       DECIMAL(10,3)  NOT NULL DEFAULT 0 CHECK (quantidade >= 0),
  id_produto       INT            NOT NULL,
  id_localizacao   INT            NOT NULL,
  status_lote      ENUM('ativo','vencido','bloqueado','quarentena','finalizado') NOT NULL DEFAULT 'ativo',
  data_bloqueio    DATETIME       NULL,
  motivo_bloqueio  TEXT           NULL,
  criado_em        DATETIME       NOT NULL DEFAULT NOW(),
  atualizado_em    DATETIME       NOT NULL DEFAULT NOW() ON UPDATE NOW(),
  PRIMARY KEY (id),
  CONSTRAINT fk_lote_produto       FOREIGN KEY (id_produto)     REFERENCES produto     (id) ON UPDATE CASCADE,
  CONSTRAINT fk_lote_localizacao   FOREIGN KEY (id_localizacao) REFERENCES localizacao (id) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -------------------------------------------------------------
-- 5. movimentacao
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS movimentacao (
  id                     INT           NOT NULL AUTO_INCREMENT,
  tipo                   ENUM('entrada','saida','transferencia','ajuste','inventario') NOT NULL,
  data_movimentacao      DATETIME      NOT NULL DEFAULT NOW(),
  quantidade             DECIMAL(10,3) NOT NULL CHECK (quantidade > 0),
  id_lote                INT           NOT NULL,
  id_usuario             INT           NOT NULL,
  id_localizacao_origem  INT           NULL,
  id_localizacao_destino INT           NULL,
  motivo_movimentacao    VARCHAR(255)  NULL,
  observacao             TEXT          NULL,
  status                 ENUM('pendente','concluida','cancelada') NOT NULL DEFAULT 'pendente',
  criado_em              DATETIME      NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id),
  CONSTRAINT fk_mov_lote        FOREIGN KEY (id_lote)                REFERENCES lote        (id) ON UPDATE CASCADE,
  CONSTRAINT fk_mov_usuario     FOREIGN KEY (id_usuario)             REFERENCES usuario     (id) ON UPDATE CASCADE,
  CONSTRAINT fk_mov_loc_origem  FOREIGN KEY (id_localizacao_origem)  REFERENCES localizacao (id) ON UPDATE CASCADE,
  CONSTRAINT fk_mov_loc_destino FOREIGN KEY (id_localizacao_destino) REFERENCES localizacao (id) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -------------------------------------------------------------
-- 6. identificacao
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS identificacao (
  id        INT          NOT NULL AUTO_INCREMENT,
  tipo      ENUM('QR Code','RFID') NOT NULL,
  codigo    VARCHAR(500) NOT NULL UNIQUE,
  id_lote   INT          NOT NULL UNIQUE,
  criado_em DATETIME     NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id),
  CONSTRAINT fk_identificacao_lote FOREIGN KEY (id_lote) REFERENCES lote (id) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -------------------------------------------------------------
-- 7. auditoria_log  (imutável: apenas INSERT permitido)
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS auditoria_log (
  id               INT          NOT NULL AUTO_INCREMENT,
  tabela_afetada   VARCHAR(100) NOT NULL,
  operacao         ENUM('INSERT','UPDATE','DELETE','LOGIN','AJUSTE','BLOQUEIO') NOT NULL,
  valor_anterior   TEXT         NULL,
  valor_novo       TEXT         NULL,
  id_usuario       INT          NULL,
  data_hora        DATETIME     NOT NULL DEFAULT NOW(),
  ip_usuario       VARCHAR(45)  NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_auditoria_usuario FOREIGN KEY (id_usuario) REFERENCES usuario (id) ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS = 1;

-- =============================================================
-- TRIGGERS DE AUDITORIA
-- =============================================================

DELIMITER $$

-- Trigger 1: auditoria após INSERT em movimentacao
DROP TRIGGER IF EXISTS trg_audit_movimentacao_insert$$
CREATE TRIGGER trg_audit_movimentacao_insert
AFTER INSERT ON movimentacao
FOR EACH ROW
BEGIN
  INSERT INTO auditoria_log (tabela_afetada, operacao, valor_novo, data_hora)
  VALUES (
    'movimentacao',
    'INSERT',
    CONCAT('tipo:', NEW.tipo, ',quantidade:', NEW.quantidade, ',id_lote:', NEW.id_lote, ',status:', NEW.status),
    NOW()
  );
END$$

-- Trigger 2: auditoria após UPDATE em lote (quantidade e/ou status)
DROP TRIGGER IF EXISTS trg_audit_lote_update$$
CREATE TRIGGER trg_audit_lote_update
AFTER UPDATE ON lote
FOR EACH ROW
BEGIN
  IF OLD.quantidade != NEW.quantidade OR OLD.status_lote != NEW.status_lote THEN
    INSERT INTO auditoria_log (tabela_afetada, operacao, valor_anterior, valor_novo, data_hora)
    VALUES (
      'lote',
      'UPDATE',
      CONCAT('quantidade:', OLD.quantidade, ',status_lote:', OLD.status_lote),
      CONCAT('quantidade:', NEW.quantidade, ',status_lote:', NEW.status_lote),
      NOW()
    );
  END IF;
END$$

-- Trigger 3: auditoria após INSERT em usuario
DROP TRIGGER IF EXISTS trg_audit_usuario_insert$$
CREATE TRIGGER trg_audit_usuario_insert
AFTER INSERT ON usuario
FOR EACH ROW
BEGIN
  INSERT INTO auditoria_log (tabela_afetada, operacao, valor_novo, data_hora)
  VALUES (
    'usuario',
    'INSERT',
    CONCAT('email:', NEW.email, ',perfil:', NEW.perfil),
    NOW()
  );
END$$

DELIMITER ;

-- =============================================================
-- SEED: dados iniciais
-- =============================================================

-- 576 localizações Arte Trigo (6 zonas × 4 corredores × 4 níveis × 6 posições)
INSERT INTO localizacao (corredor, nivel, posicao, descricao) VALUES
  ('CF01-A', 1, 1, 'CF-01 Câmara Fria Pães -18°C · Corredor A · Nível 1 · Posição 1'),
  ('CF01-A', 1, 2, 'CF-01 Câmara Fria Pães -18°C · Corredor A · Nível 1 · Posição 2'),
  ('CF01-A', 1, 3, 'CF-01 Câmara Fria Pães -18°C · Corredor A · Nível 1 · Posição 3'),
  ('CF01-A', 1, 4, 'CF-01 Câmara Fria Pães -18°C · Corredor A · Nível 1 · Posição 4'),
  ('CF01-A', 1, 5, 'CF-01 Câmara Fria Pães -18°C · Corredor A · Nível 1 · Posição 5'),
  ('CF01-A', 1, 6, 'CF-01 Câmara Fria Pães -18°C · Corredor A · Nível 1 · Posição 6'),
  ('CF01-A', 2, 1, 'CF-01 Câmara Fria Pães -18°C · Corredor A · Nível 2 · Posição 1'),
  ('CF01-A', 2, 2, 'CF-01 Câmara Fria Pães -18°C · Corredor A · Nível 2 · Posição 2'),
  ('CF01-A', 2, 3, 'CF-01 Câmara Fria Pães -18°C · Corredor A · Nível 2 · Posição 3'),
  ('CF01-A', 2, 4, 'CF-01 Câmara Fria Pães -18°C · Corredor A · Nível 2 · Posição 4'),
  ('CF01-A', 2, 5, 'CF-01 Câmara Fria Pães -18°C · Corredor A · Nível 2 · Posição 5'),
  ('CF01-A', 2, 6, 'CF-01 Câmara Fria Pães -18°C · Corredor A · Nível 2 · Posição 6'),
  ('CF01-A', 3, 1, 'CF-01 Câmara Fria Pães -18°C · Corredor A · Nível 3 · Posição 1'),
  ('CF01-A', 3, 2, 'CF-01 Câmara Fria Pães -18°C · Corredor A · Nível 3 · Posição 2'),
  ('CF01-A', 3, 3, 'CF-01 Câmara Fria Pães -18°C · Corredor A · Nível 3 · Posição 3'),
  ('CF01-A', 3, 4, 'CF-01 Câmara Fria Pães -18°C · Corredor A · Nível 3 · Posição 4'),
  ('CF01-A', 3, 5, 'CF-01 Câmara Fria Pães -18°C · Corredor A · Nível 3 · Posição 5'),
  ('CF01-A', 3, 6, 'CF-01 Câmara Fria Pães -18°C · Corredor A · Nível 3 · Posição 6'),
  ('CF01-A', 4, 1, 'CF-01 Câmara Fria Pães -18°C · Corredor A · Nível 4 · Posição 1'),
  ('CF01-A', 4, 2, 'CF-01 Câmara Fria Pães -18°C · Corredor A · Nível 4 · Posição 2'),
  ('CF01-A', 4, 3, 'CF-01 Câmara Fria Pães -18°C · Corredor A · Nível 4 · Posição 3'),
  ('CF01-A', 4, 4, 'CF-01 Câmara Fria Pães -18°C · Corredor A · Nível 4 · Posição 4'),
  ('CF01-A', 4, 5, 'CF-01 Câmara Fria Pães -18°C · Corredor A · Nível 4 · Posição 5'),
  ('CF01-A', 4, 6, 'CF-01 Câmara Fria Pães -18°C · Corredor A · Nível 4 · Posição 6'),
  ('CF01-B', 1, 1, 'CF-01 Câmara Fria Pães -18°C · Corredor B · Nível 1 · Posição 1'),
  ('CF01-B', 1, 2, 'CF-01 Câmara Fria Pães -18°C · Corredor B · Nível 1 · Posição 2'),
  ('CF01-B', 1, 3, 'CF-01 Câmara Fria Pães -18°C · Corredor B · Nível 1 · Posição 3'),
  ('CF01-B', 1, 4, 'CF-01 Câmara Fria Pães -18°C · Corredor B · Nível 1 · Posição 4'),
  ('CF01-B', 1, 5, 'CF-01 Câmara Fria Pães -18°C · Corredor B · Nível 1 · Posição 5'),
  ('CF01-B', 1, 6, 'CF-01 Câmara Fria Pães -18°C · Corredor B · Nível 1 · Posição 6'),
  ('CF01-B', 2, 1, 'CF-01 Câmara Fria Pães -18°C · Corredor B · Nível 2 · Posição 1'),
  ('CF01-B', 2, 2, 'CF-01 Câmara Fria Pães -18°C · Corredor B · Nível 2 · Posição 2'),
  ('CF01-B', 2, 3, 'CF-01 Câmara Fria Pães -18°C · Corredor B · Nível 2 · Posição 3'),
  ('CF01-B', 2, 4, 'CF-01 Câmara Fria Pães -18°C · Corredor B · Nível 2 · Posição 4'),
  ('CF01-B', 2, 5, 'CF-01 Câmara Fria Pães -18°C · Corredor B · Nível 2 · Posição 5'),
  ('CF01-B', 2, 6, 'CF-01 Câmara Fria Pães -18°C · Corredor B · Nível 2 · Posição 6'),
  ('CF01-B', 3, 1, 'CF-01 Câmara Fria Pães -18°C · Corredor B · Nível 3 · Posição 1'),
  ('CF01-B', 3, 2, 'CF-01 Câmara Fria Pães -18°C · Corredor B · Nível 3 · Posição 2'),
  ('CF01-B', 3, 3, 'CF-01 Câmara Fria Pães -18°C · Corredor B · Nível 3 · Posição 3'),
  ('CF01-B', 3, 4, 'CF-01 Câmara Fria Pães -18°C · Corredor B · Nível 3 · Posição 4'),
  ('CF01-B', 3, 5, 'CF-01 Câmara Fria Pães -18°C · Corredor B · Nível 3 · Posição 5'),
  ('CF01-B', 3, 6, 'CF-01 Câmara Fria Pães -18°C · Corredor B · Nível 3 · Posição 6'),
  ('CF01-B', 4, 1, 'CF-01 Câmara Fria Pães -18°C · Corredor B · Nível 4 · Posição 1'),
  ('CF01-B', 4, 2, 'CF-01 Câmara Fria Pães -18°C · Corredor B · Nível 4 · Posição 2'),
  ('CF01-B', 4, 3, 'CF-01 Câmara Fria Pães -18°C · Corredor B · Nível 4 · Posição 3'),
  ('CF01-B', 4, 4, 'CF-01 Câmara Fria Pães -18°C · Corredor B · Nível 4 · Posição 4'),
  ('CF01-B', 4, 5, 'CF-01 Câmara Fria Pães -18°C · Corredor B · Nível 4 · Posição 5'),
  ('CF01-B', 4, 6, 'CF-01 Câmara Fria Pães -18°C · Corredor B · Nível 4 · Posição 6'),
  ('CF01-C', 1, 1, 'CF-01 Câmara Fria Pães -18°C · Corredor C · Nível 1 · Posição 1'),
  ('CF01-C', 1, 2, 'CF-01 Câmara Fria Pães -18°C · Corredor C · Nível 1 · Posição 2'),
  ('CF01-C', 1, 3, 'CF-01 Câmara Fria Pães -18°C · Corredor C · Nível 1 · Posição 3'),
  ('CF01-C', 1, 4, 'CF-01 Câmara Fria Pães -18°C · Corredor C · Nível 1 · Posição 4'),
  ('CF01-C', 1, 5, 'CF-01 Câmara Fria Pães -18°C · Corredor C · Nível 1 · Posição 5'),
  ('CF01-C', 1, 6, 'CF-01 Câmara Fria Pães -18°C · Corredor C · Nível 1 · Posição 6'),
  ('CF01-C', 2, 1, 'CF-01 Câmara Fria Pães -18°C · Corredor C · Nível 2 · Posição 1'),
  ('CF01-C', 2, 2, 'CF-01 Câmara Fria Pães -18°C · Corredor C · Nível 2 · Posição 2'),
  ('CF01-C', 2, 3, 'CF-01 Câmara Fria Pães -18°C · Corredor C · Nível 2 · Posição 3'),
  ('CF01-C', 2, 4, 'CF-01 Câmara Fria Pães -18°C · Corredor C · Nível 2 · Posição 4'),
  ('CF01-C', 2, 5, 'CF-01 Câmara Fria Pães -18°C · Corredor C · Nível 2 · Posição 5'),
  ('CF01-C', 2, 6, 'CF-01 Câmara Fria Pães -18°C · Corredor C · Nível 2 · Posição 6'),
  ('CF01-C', 3, 1, 'CF-01 Câmara Fria Pães -18°C · Corredor C · Nível 3 · Posição 1'),
  ('CF01-C', 3, 2, 'CF-01 Câmara Fria Pães -18°C · Corredor C · Nível 3 · Posição 2'),
  ('CF01-C', 3, 3, 'CF-01 Câmara Fria Pães -18°C · Corredor C · Nível 3 · Posição 3'),
  ('CF01-C', 3, 4, 'CF-01 Câmara Fria Pães -18°C · Corredor C · Nível 3 · Posição 4'),
  ('CF01-C', 3, 5, 'CF-01 Câmara Fria Pães -18°C · Corredor C · Nível 3 · Posição 5'),
  ('CF01-C', 3, 6, 'CF-01 Câmara Fria Pães -18°C · Corredor C · Nível 3 · Posição 6'),
  ('CF01-C', 4, 1, 'CF-01 Câmara Fria Pães -18°C · Corredor C · Nível 4 · Posição 1'),
  ('CF01-C', 4, 2, 'CF-01 Câmara Fria Pães -18°C · Corredor C · Nível 4 · Posição 2'),
  ('CF01-C', 4, 3, 'CF-01 Câmara Fria Pães -18°C · Corredor C · Nível 4 · Posição 3'),
  ('CF01-C', 4, 4, 'CF-01 Câmara Fria Pães -18°C · Corredor C · Nível 4 · Posição 4'),
  ('CF01-C', 4, 5, 'CF-01 Câmara Fria Pães -18°C · Corredor C · Nível 4 · Posição 5'),
  ('CF01-C', 4, 6, 'CF-01 Câmara Fria Pães -18°C · Corredor C · Nível 4 · Posição 6'),
  ('CF01-D', 1, 1, 'CF-01 Câmara Fria Pães -18°C · Corredor D · Nível 1 · Posição 1'),
  ('CF01-D', 1, 2, 'CF-01 Câmara Fria Pães -18°C · Corredor D · Nível 1 · Posição 2'),
  ('CF01-D', 1, 3, 'CF-01 Câmara Fria Pães -18°C · Corredor D · Nível 1 · Posição 3'),
  ('CF01-D', 1, 4, 'CF-01 Câmara Fria Pães -18°C · Corredor D · Nível 1 · Posição 4'),
  ('CF01-D', 1, 5, 'CF-01 Câmara Fria Pães -18°C · Corredor D · Nível 1 · Posição 5'),
  ('CF01-D', 1, 6, 'CF-01 Câmara Fria Pães -18°C · Corredor D · Nível 1 · Posição 6'),
  ('CF01-D', 2, 1, 'CF-01 Câmara Fria Pães -18°C · Corredor D · Nível 2 · Posição 1'),
  ('CF01-D', 2, 2, 'CF-01 Câmara Fria Pães -18°C · Corredor D · Nível 2 · Posição 2'),
  ('CF01-D', 2, 3, 'CF-01 Câmara Fria Pães -18°C · Corredor D · Nível 2 · Posição 3'),
  ('CF01-D', 2, 4, 'CF-01 Câmara Fria Pães -18°C · Corredor D · Nível 2 · Posição 4'),
  ('CF01-D', 2, 5, 'CF-01 Câmara Fria Pães -18°C · Corredor D · Nível 2 · Posição 5'),
  ('CF01-D', 2, 6, 'CF-01 Câmara Fria Pães -18°C · Corredor D · Nível 2 · Posição 6'),
  ('CF01-D', 3, 1, 'CF-01 Câmara Fria Pães -18°C · Corredor D · Nível 3 · Posição 1'),
  ('CF01-D', 3, 2, 'CF-01 Câmara Fria Pães -18°C · Corredor D · Nível 3 · Posição 2'),
  ('CF01-D', 3, 3, 'CF-01 Câmara Fria Pães -18°C · Corredor D · Nível 3 · Posição 3'),
  ('CF01-D', 3, 4, 'CF-01 Câmara Fria Pães -18°C · Corredor D · Nível 3 · Posição 4'),
  ('CF01-D', 3, 5, 'CF-01 Câmara Fria Pães -18°C · Corredor D · Nível 3 · Posição 5'),
  ('CF01-D', 3, 6, 'CF-01 Câmara Fria Pães -18°C · Corredor D · Nível 3 · Posição 6'),
  ('CF01-D', 4, 1, 'CF-01 Câmara Fria Pães -18°C · Corredor D · Nível 4 · Posição 1'),
  ('CF01-D', 4, 2, 'CF-01 Câmara Fria Pães -18°C · Corredor D · Nível 4 · Posição 2'),
  ('CF01-D', 4, 3, 'CF-01 Câmara Fria Pães -18°C · Corredor D · Nível 4 · Posição 3'),
  ('CF01-D', 4, 4, 'CF-01 Câmara Fria Pães -18°C · Corredor D · Nível 4 · Posição 4'),
  ('CF01-D', 4, 5, 'CF-01 Câmara Fria Pães -18°C · Corredor D · Nível 4 · Posição 5'),
  ('CF01-D', 4, 6, 'CF-01 Câmara Fria Pães -18°C · Corredor D · Nível 4 · Posição 6'),
  ('CF02-A', 1, 1, 'CF-02 Salgados -18°C · Corredor A · Nível 1 · Posição 1'),
  ('CF02-A', 1, 2, 'CF-02 Salgados -18°C · Corredor A · Nível 1 · Posição 2'),
  ('CF02-A', 1, 3, 'CF-02 Salgados -18°C · Corredor A · Nível 1 · Posição 3'),
  ('CF02-A', 1, 4, 'CF-02 Salgados -18°C · Corredor A · Nível 1 · Posição 4'),
  ('CF02-A', 1, 5, 'CF-02 Salgados -18°C · Corredor A · Nível 1 · Posição 5'),
  ('CF02-A', 1, 6, 'CF-02 Salgados -18°C · Corredor A · Nível 1 · Posição 6'),
  ('CF02-A', 2, 1, 'CF-02 Salgados -18°C · Corredor A · Nível 2 · Posição 1'),
  ('CF02-A', 2, 2, 'CF-02 Salgados -18°C · Corredor A · Nível 2 · Posição 2'),
  ('CF02-A', 2, 3, 'CF-02 Salgados -18°C · Corredor A · Nível 2 · Posição 3'),
  ('CF02-A', 2, 4, 'CF-02 Salgados -18°C · Corredor A · Nível 2 · Posição 4'),
  ('CF02-A', 2, 5, 'CF-02 Salgados -18°C · Corredor A · Nível 2 · Posição 5'),
  ('CF02-A', 2, 6, 'CF-02 Salgados -18°C · Corredor A · Nível 2 · Posição 6'),
  ('CF02-A', 3, 1, 'CF-02 Salgados -18°C · Corredor A · Nível 3 · Posição 1'),
  ('CF02-A', 3, 2, 'CF-02 Salgados -18°C · Corredor A · Nível 3 · Posição 2'),
  ('CF02-A', 3, 3, 'CF-02 Salgados -18°C · Corredor A · Nível 3 · Posição 3'),
  ('CF02-A', 3, 4, 'CF-02 Salgados -18°C · Corredor A · Nível 3 · Posição 4'),
  ('CF02-A', 3, 5, 'CF-02 Salgados -18°C · Corredor A · Nível 3 · Posição 5'),
  ('CF02-A', 3, 6, 'CF-02 Salgados -18°C · Corredor A · Nível 3 · Posição 6'),
  ('CF02-A', 4, 1, 'CF-02 Salgados -18°C · Corredor A · Nível 4 · Posição 1'),
  ('CF02-A', 4, 2, 'CF-02 Salgados -18°C · Corredor A · Nível 4 · Posição 2'),
  ('CF02-A', 4, 3, 'CF-02 Salgados -18°C · Corredor A · Nível 4 · Posição 3'),
  ('CF02-A', 4, 4, 'CF-02 Salgados -18°C · Corredor A · Nível 4 · Posição 4'),
  ('CF02-A', 4, 5, 'CF-02 Salgados -18°C · Corredor A · Nível 4 · Posição 5'),
  ('CF02-A', 4, 6, 'CF-02 Salgados -18°C · Corredor A · Nível 4 · Posição 6'),
  ('CF02-B', 1, 1, 'CF-02 Salgados -18°C · Corredor B · Nível 1 · Posição 1'),
  ('CF02-B', 1, 2, 'CF-02 Salgados -18°C · Corredor B · Nível 1 · Posição 2'),
  ('CF02-B', 1, 3, 'CF-02 Salgados -18°C · Corredor B · Nível 1 · Posição 3'),
  ('CF02-B', 1, 4, 'CF-02 Salgados -18°C · Corredor B · Nível 1 · Posição 4'),
  ('CF02-B', 1, 5, 'CF-02 Salgados -18°C · Corredor B · Nível 1 · Posição 5'),
  ('CF02-B', 1, 6, 'CF-02 Salgados -18°C · Corredor B · Nível 1 · Posição 6'),
  ('CF02-B', 2, 1, 'CF-02 Salgados -18°C · Corredor B · Nível 2 · Posição 1'),
  ('CF02-B', 2, 2, 'CF-02 Salgados -18°C · Corredor B · Nível 2 · Posição 2'),
  ('CF02-B', 2, 3, 'CF-02 Salgados -18°C · Corredor B · Nível 2 · Posição 3'),
  ('CF02-B', 2, 4, 'CF-02 Salgados -18°C · Corredor B · Nível 2 · Posição 4'),
  ('CF02-B', 2, 5, 'CF-02 Salgados -18°C · Corredor B · Nível 2 · Posição 5'),
  ('CF02-B', 2, 6, 'CF-02 Salgados -18°C · Corredor B · Nível 2 · Posição 6'),
  ('CF02-B', 3, 1, 'CF-02 Salgados -18°C · Corredor B · Nível 3 · Posição 1'),
  ('CF02-B', 3, 2, 'CF-02 Salgados -18°C · Corredor B · Nível 3 · Posição 2'),
  ('CF02-B', 3, 3, 'CF-02 Salgados -18°C · Corredor B · Nível 3 · Posição 3'),
  ('CF02-B', 3, 4, 'CF-02 Salgados -18°C · Corredor B · Nível 3 · Posição 4'),
  ('CF02-B', 3, 5, 'CF-02 Salgados -18°C · Corredor B · Nível 3 · Posição 5'),
  ('CF02-B', 3, 6, 'CF-02 Salgados -18°C · Corredor B · Nível 3 · Posição 6'),
  ('CF02-B', 4, 1, 'CF-02 Salgados -18°C · Corredor B · Nível 4 · Posição 1'),
  ('CF02-B', 4, 2, 'CF-02 Salgados -18°C · Corredor B · Nível 4 · Posição 2'),
  ('CF02-B', 4, 3, 'CF-02 Salgados -18°C · Corredor B · Nível 4 · Posição 3'),
  ('CF02-B', 4, 4, 'CF-02 Salgados -18°C · Corredor B · Nível 4 · Posição 4'),
  ('CF02-B', 4, 5, 'CF-02 Salgados -18°C · Corredor B · Nível 4 · Posição 5'),
  ('CF02-B', 4, 6, 'CF-02 Salgados -18°C · Corredor B · Nível 4 · Posição 6'),
  ('CF02-C', 1, 1, 'CF-02 Salgados -18°C · Corredor C · Nível 1 · Posição 1'),
  ('CF02-C', 1, 2, 'CF-02 Salgados -18°C · Corredor C · Nível 1 · Posição 2'),
  ('CF02-C', 1, 3, 'CF-02 Salgados -18°C · Corredor C · Nível 1 · Posição 3'),
  ('CF02-C', 1, 4, 'CF-02 Salgados -18°C · Corredor C · Nível 1 · Posição 4'),
  ('CF02-C', 1, 5, 'CF-02 Salgados -18°C · Corredor C · Nível 1 · Posição 5'),
  ('CF02-C', 1, 6, 'CF-02 Salgados -18°C · Corredor C · Nível 1 · Posição 6'),
  ('CF02-C', 2, 1, 'CF-02 Salgados -18°C · Corredor C · Nível 2 · Posição 1'),
  ('CF02-C', 2, 2, 'CF-02 Salgados -18°C · Corredor C · Nível 2 · Posição 2'),
  ('CF02-C', 2, 3, 'CF-02 Salgados -18°C · Corredor C · Nível 2 · Posição 3'),
  ('CF02-C', 2, 4, 'CF-02 Salgados -18°C · Corredor C · Nível 2 · Posição 4'),
  ('CF02-C', 2, 5, 'CF-02 Salgados -18°C · Corredor C · Nível 2 · Posição 5'),
  ('CF02-C', 2, 6, 'CF-02 Salgados -18°C · Corredor C · Nível 2 · Posição 6'),
  ('CF02-C', 3, 1, 'CF-02 Salgados -18°C · Corredor C · Nível 3 · Posição 1'),
  ('CF02-C', 3, 2, 'CF-02 Salgados -18°C · Corredor C · Nível 3 · Posição 2'),
  ('CF02-C', 3, 3, 'CF-02 Salgados -18°C · Corredor C · Nível 3 · Posição 3'),
  ('CF02-C', 3, 4, 'CF-02 Salgados -18°C · Corredor C · Nível 3 · Posição 4'),
  ('CF02-C', 3, 5, 'CF-02 Salgados -18°C · Corredor C · Nível 3 · Posição 5'),
  ('CF02-C', 3, 6, 'CF-02 Salgados -18°C · Corredor C · Nível 3 · Posição 6'),
  ('CF02-C', 4, 1, 'CF-02 Salgados -18°C · Corredor C · Nível 4 · Posição 1'),
  ('CF02-C', 4, 2, 'CF-02 Salgados -18°C · Corredor C · Nível 4 · Posição 2'),
  ('CF02-C', 4, 3, 'CF-02 Salgados -18°C · Corredor C · Nível 4 · Posição 3'),
  ('CF02-C', 4, 4, 'CF-02 Salgados -18°C · Corredor C · Nível 4 · Posição 4'),
  ('CF02-C', 4, 5, 'CF-02 Salgados -18°C · Corredor C · Nível 4 · Posição 5'),
  ('CF02-C', 4, 6, 'CF-02 Salgados -18°C · Corredor C · Nível 4 · Posição 6'),
  ('CF02-D', 1, 1, 'CF-02 Salgados -18°C · Corredor D · Nível 1 · Posição 1'),
  ('CF02-D', 1, 2, 'CF-02 Salgados -18°C · Corredor D · Nível 1 · Posição 2'),
  ('CF02-D', 1, 3, 'CF-02 Salgados -18°C · Corredor D · Nível 1 · Posição 3'),
  ('CF02-D', 1, 4, 'CF-02 Salgados -18°C · Corredor D · Nível 1 · Posição 4'),
  ('CF02-D', 1, 5, 'CF-02 Salgados -18°C · Corredor D · Nível 1 · Posição 5'),
  ('CF02-D', 1, 6, 'CF-02 Salgados -18°C · Corredor D · Nível 1 · Posição 6'),
  ('CF02-D', 2, 1, 'CF-02 Salgados -18°C · Corredor D · Nível 2 · Posição 1'),
  ('CF02-D', 2, 2, 'CF-02 Salgados -18°C · Corredor D · Nível 2 · Posição 2'),
  ('CF02-D', 2, 3, 'CF-02 Salgados -18°C · Corredor D · Nível 2 · Posição 3'),
  ('CF02-D', 2, 4, 'CF-02 Salgados -18°C · Corredor D · Nível 2 · Posição 4'),
  ('CF02-D', 2, 5, 'CF-02 Salgados -18°C · Corredor D · Nível 2 · Posição 5'),
  ('CF02-D', 2, 6, 'CF-02 Salgados -18°C · Corredor D · Nível 2 · Posição 6'),
  ('CF02-D', 3, 1, 'CF-02 Salgados -18°C · Corredor D · Nível 3 · Posição 1'),
  ('CF02-D', 3, 2, 'CF-02 Salgados -18°C · Corredor D · Nível 3 · Posição 2'),
  ('CF02-D', 3, 3, 'CF-02 Salgados -18°C · Corredor D · Nível 3 · Posição 3'),
  ('CF02-D', 3, 4, 'CF-02 Salgados -18°C · Corredor D · Nível 3 · Posição 4'),
  ('CF02-D', 3, 5, 'CF-02 Salgados -18°C · Corredor D · Nível 3 · Posição 5'),
  ('CF02-D', 3, 6, 'CF-02 Salgados -18°C · Corredor D · Nível 3 · Posição 6'),
  ('CF02-D', 4, 1, 'CF-02 Salgados -18°C · Corredor D · Nível 4 · Posição 1'),
  ('CF02-D', 4, 2, 'CF-02 Salgados -18°C · Corredor D · Nível 4 · Posição 2'),
  ('CF02-D', 4, 3, 'CF-02 Salgados -18°C · Corredor D · Nível 4 · Posição 3'),
  ('CF02-D', 4, 4, 'CF-02 Salgados -18°C · Corredor D · Nível 4 · Posição 4'),
  ('CF02-D', 4, 5, 'CF-02 Salgados -18°C · Corredor D · Nível 4 · Posição 5'),
  ('CF02-D', 4, 6, 'CF-02 Salgados -18°C · Corredor D · Nível 4 · Posição 6'),
  ('CF03-A', 1, 1, 'CF-03 Quitandas -18°C · Corredor A · Nível 1 · Posição 1'),
  ('CF03-A', 1, 2, 'CF-03 Quitandas -18°C · Corredor A · Nível 1 · Posição 2'),
  ('CF03-A', 1, 3, 'CF-03 Quitandas -18°C · Corredor A · Nível 1 · Posição 3'),
  ('CF03-A', 1, 4, 'CF-03 Quitandas -18°C · Corredor A · Nível 1 · Posição 4'),
  ('CF03-A', 1, 5, 'CF-03 Quitandas -18°C · Corredor A · Nível 1 · Posição 5'),
  ('CF03-A', 1, 6, 'CF-03 Quitandas -18°C · Corredor A · Nível 1 · Posição 6'),
  ('CF03-A', 2, 1, 'CF-03 Quitandas -18°C · Corredor A · Nível 2 · Posição 1'),
  ('CF03-A', 2, 2, 'CF-03 Quitandas -18°C · Corredor A · Nível 2 · Posição 2'),
  ('CF03-A', 2, 3, 'CF-03 Quitandas -18°C · Corredor A · Nível 2 · Posição 3'),
  ('CF03-A', 2, 4, 'CF-03 Quitandas -18°C · Corredor A · Nível 2 · Posição 4'),
  ('CF03-A', 2, 5, 'CF-03 Quitandas -18°C · Corredor A · Nível 2 · Posição 5'),
  ('CF03-A', 2, 6, 'CF-03 Quitandas -18°C · Corredor A · Nível 2 · Posição 6'),
  ('CF03-A', 3, 1, 'CF-03 Quitandas -18°C · Corredor A · Nível 3 · Posição 1'),
  ('CF03-A', 3, 2, 'CF-03 Quitandas -18°C · Corredor A · Nível 3 · Posição 2'),
  ('CF03-A', 3, 3, 'CF-03 Quitandas -18°C · Corredor A · Nível 3 · Posição 3'),
  ('CF03-A', 3, 4, 'CF-03 Quitandas -18°C · Corredor A · Nível 3 · Posição 4'),
  ('CF03-A', 3, 5, 'CF-03 Quitandas -18°C · Corredor A · Nível 3 · Posição 5'),
  ('CF03-A', 3, 6, 'CF-03 Quitandas -18°C · Corredor A · Nível 3 · Posição 6'),
  ('CF03-A', 4, 1, 'CF-03 Quitandas -18°C · Corredor A · Nível 4 · Posição 1'),
  ('CF03-A', 4, 2, 'CF-03 Quitandas -18°C · Corredor A · Nível 4 · Posição 2'),
  ('CF03-A', 4, 3, 'CF-03 Quitandas -18°C · Corredor A · Nível 4 · Posição 3'),
  ('CF03-A', 4, 4, 'CF-03 Quitandas -18°C · Corredor A · Nível 4 · Posição 4'),
  ('CF03-A', 4, 5, 'CF-03 Quitandas -18°C · Corredor A · Nível 4 · Posição 5'),
  ('CF03-A', 4, 6, 'CF-03 Quitandas -18°C · Corredor A · Nível 4 · Posição 6'),
  ('CF03-B', 1, 1, 'CF-03 Quitandas -18°C · Corredor B · Nível 1 · Posição 1'),
  ('CF03-B', 1, 2, 'CF-03 Quitandas -18°C · Corredor B · Nível 1 · Posição 2'),
  ('CF03-B', 1, 3, 'CF-03 Quitandas -18°C · Corredor B · Nível 1 · Posição 3'),
  ('CF03-B', 1, 4, 'CF-03 Quitandas -18°C · Corredor B · Nível 1 · Posição 4'),
  ('CF03-B', 1, 5, 'CF-03 Quitandas -18°C · Corredor B · Nível 1 · Posição 5'),
  ('CF03-B', 1, 6, 'CF-03 Quitandas -18°C · Corredor B · Nível 1 · Posição 6'),
  ('CF03-B', 2, 1, 'CF-03 Quitandas -18°C · Corredor B · Nível 2 · Posição 1'),
  ('CF03-B', 2, 2, 'CF-03 Quitandas -18°C · Corredor B · Nível 2 · Posição 2'),
  ('CF03-B', 2, 3, 'CF-03 Quitandas -18°C · Corredor B · Nível 2 · Posição 3'),
  ('CF03-B', 2, 4, 'CF-03 Quitandas -18°C · Corredor B · Nível 2 · Posição 4'),
  ('CF03-B', 2, 5, 'CF-03 Quitandas -18°C · Corredor B · Nível 2 · Posição 5'),
  ('CF03-B', 2, 6, 'CF-03 Quitandas -18°C · Corredor B · Nível 2 · Posição 6'),
  ('CF03-B', 3, 1, 'CF-03 Quitandas -18°C · Corredor B · Nível 3 · Posição 1'),
  ('CF03-B', 3, 2, 'CF-03 Quitandas -18°C · Corredor B · Nível 3 · Posição 2'),
  ('CF03-B', 3, 3, 'CF-03 Quitandas -18°C · Corredor B · Nível 3 · Posição 3'),
  ('CF03-B', 3, 4, 'CF-03 Quitandas -18°C · Corredor B · Nível 3 · Posição 4'),
  ('CF03-B', 3, 5, 'CF-03 Quitandas -18°C · Corredor B · Nível 3 · Posição 5'),
  ('CF03-B', 3, 6, 'CF-03 Quitandas -18°C · Corredor B · Nível 3 · Posição 6'),
  ('CF03-B', 4, 1, 'CF-03 Quitandas -18°C · Corredor B · Nível 4 · Posição 1'),
  ('CF03-B', 4, 2, 'CF-03 Quitandas -18°C · Corredor B · Nível 4 · Posição 2'),
  ('CF03-B', 4, 3, 'CF-03 Quitandas -18°C · Corredor B · Nível 4 · Posição 3'),
  ('CF03-B', 4, 4, 'CF-03 Quitandas -18°C · Corredor B · Nível 4 · Posição 4'),
  ('CF03-B', 4, 5, 'CF-03 Quitandas -18°C · Corredor B · Nível 4 · Posição 5'),
  ('CF03-B', 4, 6, 'CF-03 Quitandas -18°C · Corredor B · Nível 4 · Posição 6'),
  ('CF03-C', 1, 1, 'CF-03 Quitandas -18°C · Corredor C · Nível 1 · Posição 1'),
  ('CF03-C', 1, 2, 'CF-03 Quitandas -18°C · Corredor C · Nível 1 · Posição 2'),
  ('CF03-C', 1, 3, 'CF-03 Quitandas -18°C · Corredor C · Nível 1 · Posição 3'),
  ('CF03-C', 1, 4, 'CF-03 Quitandas -18°C · Corredor C · Nível 1 · Posição 4'),
  ('CF03-C', 1, 5, 'CF-03 Quitandas -18°C · Corredor C · Nível 1 · Posição 5'),
  ('CF03-C', 1, 6, 'CF-03 Quitandas -18°C · Corredor C · Nível 1 · Posição 6'),
  ('CF03-C', 2, 1, 'CF-03 Quitandas -18°C · Corredor C · Nível 2 · Posição 1'),
  ('CF03-C', 2, 2, 'CF-03 Quitandas -18°C · Corredor C · Nível 2 · Posição 2'),
  ('CF03-C', 2, 3, 'CF-03 Quitandas -18°C · Corredor C · Nível 2 · Posição 3'),
  ('CF03-C', 2, 4, 'CF-03 Quitandas -18°C · Corredor C · Nível 2 · Posição 4'),
  ('CF03-C', 2, 5, 'CF-03 Quitandas -18°C · Corredor C · Nível 2 · Posição 5'),
  ('CF03-C', 2, 6, 'CF-03 Quitandas -18°C · Corredor C · Nível 2 · Posição 6'),
  ('CF03-C', 3, 1, 'CF-03 Quitandas -18°C · Corredor C · Nível 3 · Posição 1'),
  ('CF03-C', 3, 2, 'CF-03 Quitandas -18°C · Corredor C · Nível 3 · Posição 2'),
  ('CF03-C', 3, 3, 'CF-03 Quitandas -18°C · Corredor C · Nível 3 · Posição 3'),
  ('CF03-C', 3, 4, 'CF-03 Quitandas -18°C · Corredor C · Nível 3 · Posição 4'),
  ('CF03-C', 3, 5, 'CF-03 Quitandas -18°C · Corredor C · Nível 3 · Posição 5'),
  ('CF03-C', 3, 6, 'CF-03 Quitandas -18°C · Corredor C · Nível 3 · Posição 6'),
  ('CF03-C', 4, 1, 'CF-03 Quitandas -18°C · Corredor C · Nível 4 · Posição 1'),
  ('CF03-C', 4, 2, 'CF-03 Quitandas -18°C · Corredor C · Nível 4 · Posição 2'),
  ('CF03-C', 4, 3, 'CF-03 Quitandas -18°C · Corredor C · Nível 4 · Posição 3'),
  ('CF03-C', 4, 4, 'CF-03 Quitandas -18°C · Corredor C · Nível 4 · Posição 4'),
  ('CF03-C', 4, 5, 'CF-03 Quitandas -18°C · Corredor C · Nível 4 · Posição 5'),
  ('CF03-C', 4, 6, 'CF-03 Quitandas -18°C · Corredor C · Nível 4 · Posição 6'),
  ('CF03-D', 1, 1, 'CF-03 Quitandas -18°C · Corredor D · Nível 1 · Posição 1'),
  ('CF03-D', 1, 2, 'CF-03 Quitandas -18°C · Corredor D · Nível 1 · Posição 2'),
  ('CF03-D', 1, 3, 'CF-03 Quitandas -18°C · Corredor D · Nível 1 · Posição 3'),
  ('CF03-D', 1, 4, 'CF-03 Quitandas -18°C · Corredor D · Nível 1 · Posição 4'),
  ('CF03-D', 1, 5, 'CF-03 Quitandas -18°C · Corredor D · Nível 1 · Posição 5'),
  ('CF03-D', 1, 6, 'CF-03 Quitandas -18°C · Corredor D · Nível 1 · Posição 6'),
  ('CF03-D', 2, 1, 'CF-03 Quitandas -18°C · Corredor D · Nível 2 · Posição 1'),
  ('CF03-D', 2, 2, 'CF-03 Quitandas -18°C · Corredor D · Nível 2 · Posição 2'),
  ('CF03-D', 2, 3, 'CF-03 Quitandas -18°C · Corredor D · Nível 2 · Posição 3'),
  ('CF03-D', 2, 4, 'CF-03 Quitandas -18°C · Corredor D · Nível 2 · Posição 4'),
  ('CF03-D', 2, 5, 'CF-03 Quitandas -18°C · Corredor D · Nível 2 · Posição 5'),
  ('CF03-D', 2, 6, 'CF-03 Quitandas -18°C · Corredor D · Nível 2 · Posição 6'),
  ('CF03-D', 3, 1, 'CF-03 Quitandas -18°C · Corredor D · Nível 3 · Posição 1'),
  ('CF03-D', 3, 2, 'CF-03 Quitandas -18°C · Corredor D · Nível 3 · Posição 2'),
  ('CF03-D', 3, 3, 'CF-03 Quitandas -18°C · Corredor D · Nível 3 · Posição 3'),
  ('CF03-D', 3, 4, 'CF-03 Quitandas -18°C · Corredor D · Nível 3 · Posição 4'),
  ('CF03-D', 3, 5, 'CF-03 Quitandas -18°C · Corredor D · Nível 3 · Posição 5'),
  ('CF03-D', 3, 6, 'CF-03 Quitandas -18°C · Corredor D · Nível 3 · Posição 6'),
  ('CF03-D', 4, 1, 'CF-03 Quitandas -18°C · Corredor D · Nível 4 · Posição 1'),
  ('CF03-D', 4, 2, 'CF-03 Quitandas -18°C · Corredor D · Nível 4 · Posição 2'),
  ('CF03-D', 4, 3, 'CF-03 Quitandas -18°C · Corredor D · Nível 4 · Posição 3'),
  ('CF03-D', 4, 4, 'CF-03 Quitandas -18°C · Corredor D · Nível 4 · Posição 4'),
  ('CF03-D', 4, 5, 'CF-03 Quitandas -18°C · Corredor D · Nível 4 · Posição 5'),
  ('CF03-D', 4, 6, 'CF-03 Quitandas -18°C · Corredor D · Nível 4 · Posição 6'),
  ('CF04-A', 1, 1, 'CF-04 Descongelamento 4°C · Corredor A · Nível 1 · Posição 1'),
  ('CF04-A', 1, 2, 'CF-04 Descongelamento 4°C · Corredor A · Nível 1 · Posição 2'),
  ('CF04-A', 1, 3, 'CF-04 Descongelamento 4°C · Corredor A · Nível 1 · Posição 3'),
  ('CF04-A', 1, 4, 'CF-04 Descongelamento 4°C · Corredor A · Nível 1 · Posição 4'),
  ('CF04-A', 1, 5, 'CF-04 Descongelamento 4°C · Corredor A · Nível 1 · Posição 5'),
  ('CF04-A', 1, 6, 'CF-04 Descongelamento 4°C · Corredor A · Nível 1 · Posição 6'),
  ('CF04-A', 2, 1, 'CF-04 Descongelamento 4°C · Corredor A · Nível 2 · Posição 1'),
  ('CF04-A', 2, 2, 'CF-04 Descongelamento 4°C · Corredor A · Nível 2 · Posição 2'),
  ('CF04-A', 2, 3, 'CF-04 Descongelamento 4°C · Corredor A · Nível 2 · Posição 3'),
  ('CF04-A', 2, 4, 'CF-04 Descongelamento 4°C · Corredor A · Nível 2 · Posição 4'),
  ('CF04-A', 2, 5, 'CF-04 Descongelamento 4°C · Corredor A · Nível 2 · Posição 5'),
  ('CF04-A', 2, 6, 'CF-04 Descongelamento 4°C · Corredor A · Nível 2 · Posição 6'),
  ('CF04-A', 3, 1, 'CF-04 Descongelamento 4°C · Corredor A · Nível 3 · Posição 1'),
  ('CF04-A', 3, 2, 'CF-04 Descongelamento 4°C · Corredor A · Nível 3 · Posição 2'),
  ('CF04-A', 3, 3, 'CF-04 Descongelamento 4°C · Corredor A · Nível 3 · Posição 3'),
  ('CF04-A', 3, 4, 'CF-04 Descongelamento 4°C · Corredor A · Nível 3 · Posição 4'),
  ('CF04-A', 3, 5, 'CF-04 Descongelamento 4°C · Corredor A · Nível 3 · Posição 5'),
  ('CF04-A', 3, 6, 'CF-04 Descongelamento 4°C · Corredor A · Nível 3 · Posição 6'),
  ('CF04-A', 4, 1, 'CF-04 Descongelamento 4°C · Corredor A · Nível 4 · Posição 1'),
  ('CF04-A', 4, 2, 'CF-04 Descongelamento 4°C · Corredor A · Nível 4 · Posição 2'),
  ('CF04-A', 4, 3, 'CF-04 Descongelamento 4°C · Corredor A · Nível 4 · Posição 3'),
  ('CF04-A', 4, 4, 'CF-04 Descongelamento 4°C · Corredor A · Nível 4 · Posição 4'),
  ('CF04-A', 4, 5, 'CF-04 Descongelamento 4°C · Corredor A · Nível 4 · Posição 5'),
  ('CF04-A', 4, 6, 'CF-04 Descongelamento 4°C · Corredor A · Nível 4 · Posição 6'),
  ('CF04-B', 1, 1, 'CF-04 Descongelamento 4°C · Corredor B · Nível 1 · Posição 1'),
  ('CF04-B', 1, 2, 'CF-04 Descongelamento 4°C · Corredor B · Nível 1 · Posição 2'),
  ('CF04-B', 1, 3, 'CF-04 Descongelamento 4°C · Corredor B · Nível 1 · Posição 3'),
  ('CF04-B', 1, 4, 'CF-04 Descongelamento 4°C · Corredor B · Nível 1 · Posição 4'),
  ('CF04-B', 1, 5, 'CF-04 Descongelamento 4°C · Corredor B · Nível 1 · Posição 5'),
  ('CF04-B', 1, 6, 'CF-04 Descongelamento 4°C · Corredor B · Nível 1 · Posição 6'),
  ('CF04-B', 2, 1, 'CF-04 Descongelamento 4°C · Corredor B · Nível 2 · Posição 1'),
  ('CF04-B', 2, 2, 'CF-04 Descongelamento 4°C · Corredor B · Nível 2 · Posição 2'),
  ('CF04-B', 2, 3, 'CF-04 Descongelamento 4°C · Corredor B · Nível 2 · Posição 3'),
  ('CF04-B', 2, 4, 'CF-04 Descongelamento 4°C · Corredor B · Nível 2 · Posição 4'),
  ('CF04-B', 2, 5, 'CF-04 Descongelamento 4°C · Corredor B · Nível 2 · Posição 5'),
  ('CF04-B', 2, 6, 'CF-04 Descongelamento 4°C · Corredor B · Nível 2 · Posição 6'),
  ('CF04-B', 3, 1, 'CF-04 Descongelamento 4°C · Corredor B · Nível 3 · Posição 1'),
  ('CF04-B', 3, 2, 'CF-04 Descongelamento 4°C · Corredor B · Nível 3 · Posição 2'),
  ('CF04-B', 3, 3, 'CF-04 Descongelamento 4°C · Corredor B · Nível 3 · Posição 3'),
  ('CF04-B', 3, 4, 'CF-04 Descongelamento 4°C · Corredor B · Nível 3 · Posição 4'),
  ('CF04-B', 3, 5, 'CF-04 Descongelamento 4°C · Corredor B · Nível 3 · Posição 5'),
  ('CF04-B', 3, 6, 'CF-04 Descongelamento 4°C · Corredor B · Nível 3 · Posição 6'),
  ('CF04-B', 4, 1, 'CF-04 Descongelamento 4°C · Corredor B · Nível 4 · Posição 1'),
  ('CF04-B', 4, 2, 'CF-04 Descongelamento 4°C · Corredor B · Nível 4 · Posição 2'),
  ('CF04-B', 4, 3, 'CF-04 Descongelamento 4°C · Corredor B · Nível 4 · Posição 3'),
  ('CF04-B', 4, 4, 'CF-04 Descongelamento 4°C · Corredor B · Nível 4 · Posição 4'),
  ('CF04-B', 4, 5, 'CF-04 Descongelamento 4°C · Corredor B · Nível 4 · Posição 5'),
  ('CF04-B', 4, 6, 'CF-04 Descongelamento 4°C · Corredor B · Nível 4 · Posição 6'),
  ('CF04-C', 1, 1, 'CF-04 Descongelamento 4°C · Corredor C · Nível 1 · Posição 1'),
  ('CF04-C', 1, 2, 'CF-04 Descongelamento 4°C · Corredor C · Nível 1 · Posição 2'),
  ('CF04-C', 1, 3, 'CF-04 Descongelamento 4°C · Corredor C · Nível 1 · Posição 3'),
  ('CF04-C', 1, 4, 'CF-04 Descongelamento 4°C · Corredor C · Nível 1 · Posição 4'),
  ('CF04-C', 1, 5, 'CF-04 Descongelamento 4°C · Corredor C · Nível 1 · Posição 5'),
  ('CF04-C', 1, 6, 'CF-04 Descongelamento 4°C · Corredor C · Nível 1 · Posição 6'),
  ('CF04-C', 2, 1, 'CF-04 Descongelamento 4°C · Corredor C · Nível 2 · Posição 1'),
  ('CF04-C', 2, 2, 'CF-04 Descongelamento 4°C · Corredor C · Nível 2 · Posição 2'),
  ('CF04-C', 2, 3, 'CF-04 Descongelamento 4°C · Corredor C · Nível 2 · Posição 3'),
  ('CF04-C', 2, 4, 'CF-04 Descongelamento 4°C · Corredor C · Nível 2 · Posição 4'),
  ('CF04-C', 2, 5, 'CF-04 Descongelamento 4°C · Corredor C · Nível 2 · Posição 5'),
  ('CF04-C', 2, 6, 'CF-04 Descongelamento 4°C · Corredor C · Nível 2 · Posição 6'),
  ('CF04-C', 3, 1, 'CF-04 Descongelamento 4°C · Corredor C · Nível 3 · Posição 1'),
  ('CF04-C', 3, 2, 'CF-04 Descongelamento 4°C · Corredor C · Nível 3 · Posição 2'),
  ('CF04-C', 3, 3, 'CF-04 Descongelamento 4°C · Corredor C · Nível 3 · Posição 3'),
  ('CF04-C', 3, 4, 'CF-04 Descongelamento 4°C · Corredor C · Nível 3 · Posição 4'),
  ('CF04-C', 3, 5, 'CF-04 Descongelamento 4°C · Corredor C · Nível 3 · Posição 5'),
  ('CF04-C', 3, 6, 'CF-04 Descongelamento 4°C · Corredor C · Nível 3 · Posição 6'),
  ('CF04-C', 4, 1, 'CF-04 Descongelamento 4°C · Corredor C · Nível 4 · Posição 1'),
  ('CF04-C', 4, 2, 'CF-04 Descongelamento 4°C · Corredor C · Nível 4 · Posição 2'),
  ('CF04-C', 4, 3, 'CF-04 Descongelamento 4°C · Corredor C · Nível 4 · Posição 3'),
  ('CF04-C', 4, 4, 'CF-04 Descongelamento 4°C · Corredor C · Nível 4 · Posição 4'),
  ('CF04-C', 4, 5, 'CF-04 Descongelamento 4°C · Corredor C · Nível 4 · Posição 5'),
  ('CF04-C', 4, 6, 'CF-04 Descongelamento 4°C · Corredor C · Nível 4 · Posição 6'),
  ('CF04-D', 1, 1, 'CF-04 Descongelamento 4°C · Corredor D · Nível 1 · Posição 1'),
  ('CF04-D', 1, 2, 'CF-04 Descongelamento 4°C · Corredor D · Nível 1 · Posição 2'),
  ('CF04-D', 1, 3, 'CF-04 Descongelamento 4°C · Corredor D · Nível 1 · Posição 3'),
  ('CF04-D', 1, 4, 'CF-04 Descongelamento 4°C · Corredor D · Nível 1 · Posição 4'),
  ('CF04-D', 1, 5, 'CF-04 Descongelamento 4°C · Corredor D · Nível 1 · Posição 5'),
  ('CF04-D', 1, 6, 'CF-04 Descongelamento 4°C · Corredor D · Nível 1 · Posição 6'),
  ('CF04-D', 2, 1, 'CF-04 Descongelamento 4°C · Corredor D · Nível 2 · Posição 1'),
  ('CF04-D', 2, 2, 'CF-04 Descongelamento 4°C · Corredor D · Nível 2 · Posição 2'),
  ('CF04-D', 2, 3, 'CF-04 Descongelamento 4°C · Corredor D · Nível 2 · Posição 3'),
  ('CF04-D', 2, 4, 'CF-04 Descongelamento 4°C · Corredor D · Nível 2 · Posição 4'),
  ('CF04-D', 2, 5, 'CF-04 Descongelamento 4°C · Corredor D · Nível 2 · Posição 5'),
  ('CF04-D', 2, 6, 'CF-04 Descongelamento 4°C · Corredor D · Nível 2 · Posição 6'),
  ('CF04-D', 3, 1, 'CF-04 Descongelamento 4°C · Corredor D · Nível 3 · Posição 1'),
  ('CF04-D', 3, 2, 'CF-04 Descongelamento 4°C · Corredor D · Nível 3 · Posição 2'),
  ('CF04-D', 3, 3, 'CF-04 Descongelamento 4°C · Corredor D · Nível 3 · Posição 3'),
  ('CF04-D', 3, 4, 'CF-04 Descongelamento 4°C · Corredor D · Nível 3 · Posição 4'),
  ('CF04-D', 3, 5, 'CF-04 Descongelamento 4°C · Corredor D · Nível 3 · Posição 5'),
  ('CF04-D', 3, 6, 'CF-04 Descongelamento 4°C · Corredor D · Nível 3 · Posição 6'),
  ('CF04-D', 4, 1, 'CF-04 Descongelamento 4°C · Corredor D · Nível 4 · Posição 1'),
  ('CF04-D', 4, 2, 'CF-04 Descongelamento 4°C · Corredor D · Nível 4 · Posição 2'),
  ('CF04-D', 4, 3, 'CF-04 Descongelamento 4°C · Corredor D · Nível 4 · Posição 3'),
  ('CF04-D', 4, 4, 'CF-04 Descongelamento 4°C · Corredor D · Nível 4 · Posição 4'),
  ('CF04-D', 4, 5, 'CF-04 Descongelamento 4°C · Corredor D · Nível 4 · Posição 5'),
  ('CF04-D', 4, 6, 'CF-04 Descongelamento 4°C · Corredor D · Nível 4 · Posição 6'),
  ('ES01-A', 1, 1, 'ES-01 Estoque Seco Embalagens · Corredor A · Nível 1 · Posição 1'),
  ('ES01-A', 1, 2, 'ES-01 Estoque Seco Embalagens · Corredor A · Nível 1 · Posição 2'),
  ('ES01-A', 1, 3, 'ES-01 Estoque Seco Embalagens · Corredor A · Nível 1 · Posição 3'),
  ('ES01-A', 1, 4, 'ES-01 Estoque Seco Embalagens · Corredor A · Nível 1 · Posição 4'),
  ('ES01-A', 1, 5, 'ES-01 Estoque Seco Embalagens · Corredor A · Nível 1 · Posição 5'),
  ('ES01-A', 1, 6, 'ES-01 Estoque Seco Embalagens · Corredor A · Nível 1 · Posição 6'),
  ('ES01-A', 2, 1, 'ES-01 Estoque Seco Embalagens · Corredor A · Nível 2 · Posição 1'),
  ('ES01-A', 2, 2, 'ES-01 Estoque Seco Embalagens · Corredor A · Nível 2 · Posição 2'),
  ('ES01-A', 2, 3, 'ES-01 Estoque Seco Embalagens · Corredor A · Nível 2 · Posição 3'),
  ('ES01-A', 2, 4, 'ES-01 Estoque Seco Embalagens · Corredor A · Nível 2 · Posição 4'),
  ('ES01-A', 2, 5, 'ES-01 Estoque Seco Embalagens · Corredor A · Nível 2 · Posição 5'),
  ('ES01-A', 2, 6, 'ES-01 Estoque Seco Embalagens · Corredor A · Nível 2 · Posição 6'),
  ('ES01-A', 3, 1, 'ES-01 Estoque Seco Embalagens · Corredor A · Nível 3 · Posição 1'),
  ('ES01-A', 3, 2, 'ES-01 Estoque Seco Embalagens · Corredor A · Nível 3 · Posição 2'),
  ('ES01-A', 3, 3, 'ES-01 Estoque Seco Embalagens · Corredor A · Nível 3 · Posição 3'),
  ('ES01-A', 3, 4, 'ES-01 Estoque Seco Embalagens · Corredor A · Nível 3 · Posição 4'),
  ('ES01-A', 3, 5, 'ES-01 Estoque Seco Embalagens · Corredor A · Nível 3 · Posição 5'),
  ('ES01-A', 3, 6, 'ES-01 Estoque Seco Embalagens · Corredor A · Nível 3 · Posição 6'),
  ('ES01-A', 4, 1, 'ES-01 Estoque Seco Embalagens · Corredor A · Nível 4 · Posição 1'),
  ('ES01-A', 4, 2, 'ES-01 Estoque Seco Embalagens · Corredor A · Nível 4 · Posição 2'),
  ('ES01-A', 4, 3, 'ES-01 Estoque Seco Embalagens · Corredor A · Nível 4 · Posição 3'),
  ('ES01-A', 4, 4, 'ES-01 Estoque Seco Embalagens · Corredor A · Nível 4 · Posição 4'),
  ('ES01-A', 4, 5, 'ES-01 Estoque Seco Embalagens · Corredor A · Nível 4 · Posição 5'),
  ('ES01-A', 4, 6, 'ES-01 Estoque Seco Embalagens · Corredor A · Nível 4 · Posição 6'),
  ('ES01-B', 1, 1, 'ES-01 Estoque Seco Embalagens · Corredor B · Nível 1 · Posição 1'),
  ('ES01-B', 1, 2, 'ES-01 Estoque Seco Embalagens · Corredor B · Nível 1 · Posição 2'),
  ('ES01-B', 1, 3, 'ES-01 Estoque Seco Embalagens · Corredor B · Nível 1 · Posição 3'),
  ('ES01-B', 1, 4, 'ES-01 Estoque Seco Embalagens · Corredor B · Nível 1 · Posição 4'),
  ('ES01-B', 1, 5, 'ES-01 Estoque Seco Embalagens · Corredor B · Nível 1 · Posição 5'),
  ('ES01-B', 1, 6, 'ES-01 Estoque Seco Embalagens · Corredor B · Nível 1 · Posição 6'),
  ('ES01-B', 2, 1, 'ES-01 Estoque Seco Embalagens · Corredor B · Nível 2 · Posição 1'),
  ('ES01-B', 2, 2, 'ES-01 Estoque Seco Embalagens · Corredor B · Nível 2 · Posição 2'),
  ('ES01-B', 2, 3, 'ES-01 Estoque Seco Embalagens · Corredor B · Nível 2 · Posição 3'),
  ('ES01-B', 2, 4, 'ES-01 Estoque Seco Embalagens · Corredor B · Nível 2 · Posição 4'),
  ('ES01-B', 2, 5, 'ES-01 Estoque Seco Embalagens · Corredor B · Nível 2 · Posição 5'),
  ('ES01-B', 2, 6, 'ES-01 Estoque Seco Embalagens · Corredor B · Nível 2 · Posição 6'),
  ('ES01-B', 3, 1, 'ES-01 Estoque Seco Embalagens · Corredor B · Nível 3 · Posição 1'),
  ('ES01-B', 3, 2, 'ES-01 Estoque Seco Embalagens · Corredor B · Nível 3 · Posição 2'),
  ('ES01-B', 3, 3, 'ES-01 Estoque Seco Embalagens · Corredor B · Nível 3 · Posição 3'),
  ('ES01-B', 3, 4, 'ES-01 Estoque Seco Embalagens · Corredor B · Nível 3 · Posição 4'),
  ('ES01-B', 3, 5, 'ES-01 Estoque Seco Embalagens · Corredor B · Nível 3 · Posição 5'),
  ('ES01-B', 3, 6, 'ES-01 Estoque Seco Embalagens · Corredor B · Nível 3 · Posição 6'),
  ('ES01-B', 4, 1, 'ES-01 Estoque Seco Embalagens · Corredor B · Nível 4 · Posição 1'),
  ('ES01-B', 4, 2, 'ES-01 Estoque Seco Embalagens · Corredor B · Nível 4 · Posição 2'),
  ('ES01-B', 4, 3, 'ES-01 Estoque Seco Embalagens · Corredor B · Nível 4 · Posição 3'),
  ('ES01-B', 4, 4, 'ES-01 Estoque Seco Embalagens · Corredor B · Nível 4 · Posição 4'),
  ('ES01-B', 4, 5, 'ES-01 Estoque Seco Embalagens · Corredor B · Nível 4 · Posição 5'),
  ('ES01-B', 4, 6, 'ES-01 Estoque Seco Embalagens · Corredor B · Nível 4 · Posição 6'),
  ('ES01-C', 1, 1, 'ES-01 Estoque Seco Embalagens · Corredor C · Nível 1 · Posição 1'),
  ('ES01-C', 1, 2, 'ES-01 Estoque Seco Embalagens · Corredor C · Nível 1 · Posição 2'),
  ('ES01-C', 1, 3, 'ES-01 Estoque Seco Embalagens · Corredor C · Nível 1 · Posição 3'),
  ('ES01-C', 1, 4, 'ES-01 Estoque Seco Embalagens · Corredor C · Nível 1 · Posição 4'),
  ('ES01-C', 1, 5, 'ES-01 Estoque Seco Embalagens · Corredor C · Nível 1 · Posição 5'),
  ('ES01-C', 1, 6, 'ES-01 Estoque Seco Embalagens · Corredor C · Nível 1 · Posição 6'),
  ('ES01-C', 2, 1, 'ES-01 Estoque Seco Embalagens · Corredor C · Nível 2 · Posição 1'),
  ('ES01-C', 2, 2, 'ES-01 Estoque Seco Embalagens · Corredor C · Nível 2 · Posição 2'),
  ('ES01-C', 2, 3, 'ES-01 Estoque Seco Embalagens · Corredor C · Nível 2 · Posição 3'),
  ('ES01-C', 2, 4, 'ES-01 Estoque Seco Embalagens · Corredor C · Nível 2 · Posição 4'),
  ('ES01-C', 2, 5, 'ES-01 Estoque Seco Embalagens · Corredor C · Nível 2 · Posição 5'),
  ('ES01-C', 2, 6, 'ES-01 Estoque Seco Embalagens · Corredor C · Nível 2 · Posição 6'),
  ('ES01-C', 3, 1, 'ES-01 Estoque Seco Embalagens · Corredor C · Nível 3 · Posição 1'),
  ('ES01-C', 3, 2, 'ES-01 Estoque Seco Embalagens · Corredor C · Nível 3 · Posição 2'),
  ('ES01-C', 3, 3, 'ES-01 Estoque Seco Embalagens · Corredor C · Nível 3 · Posição 3'),
  ('ES01-C', 3, 4, 'ES-01 Estoque Seco Embalagens · Corredor C · Nível 3 · Posição 4'),
  ('ES01-C', 3, 5, 'ES-01 Estoque Seco Embalagens · Corredor C · Nível 3 · Posição 5'),
  ('ES01-C', 3, 6, 'ES-01 Estoque Seco Embalagens · Corredor C · Nível 3 · Posição 6'),
  ('ES01-C', 4, 1, 'ES-01 Estoque Seco Embalagens · Corredor C · Nível 4 · Posição 1'),
  ('ES01-C', 4, 2, 'ES-01 Estoque Seco Embalagens · Corredor C · Nível 4 · Posição 2'),
  ('ES01-C', 4, 3, 'ES-01 Estoque Seco Embalagens · Corredor C · Nível 4 · Posição 3'),
  ('ES01-C', 4, 4, 'ES-01 Estoque Seco Embalagens · Corredor C · Nível 4 · Posição 4'),
  ('ES01-C', 4, 5, 'ES-01 Estoque Seco Embalagens · Corredor C · Nível 4 · Posição 5'),
  ('ES01-C', 4, 6, 'ES-01 Estoque Seco Embalagens · Corredor C · Nível 4 · Posição 6'),
  ('ES01-D', 1, 1, 'ES-01 Estoque Seco Embalagens · Corredor D · Nível 1 · Posição 1'),
  ('ES01-D', 1, 2, 'ES-01 Estoque Seco Embalagens · Corredor D · Nível 1 · Posição 2'),
  ('ES01-D', 1, 3, 'ES-01 Estoque Seco Embalagens · Corredor D · Nível 1 · Posição 3'),
  ('ES01-D', 1, 4, 'ES-01 Estoque Seco Embalagens · Corredor D · Nível 1 · Posição 4'),
  ('ES01-D', 1, 5, 'ES-01 Estoque Seco Embalagens · Corredor D · Nível 1 · Posição 5'),
  ('ES01-D', 1, 6, 'ES-01 Estoque Seco Embalagens · Corredor D · Nível 1 · Posição 6'),
  ('ES01-D', 2, 1, 'ES-01 Estoque Seco Embalagens · Corredor D · Nível 2 · Posição 1'),
  ('ES01-D', 2, 2, 'ES-01 Estoque Seco Embalagens · Corredor D · Nível 2 · Posição 2'),
  ('ES01-D', 2, 3, 'ES-01 Estoque Seco Embalagens · Corredor D · Nível 2 · Posição 3'),
  ('ES01-D', 2, 4, 'ES-01 Estoque Seco Embalagens · Corredor D · Nível 2 · Posição 4'),
  ('ES01-D', 2, 5, 'ES-01 Estoque Seco Embalagens · Corredor D · Nível 2 · Posição 5'),
  ('ES01-D', 2, 6, 'ES-01 Estoque Seco Embalagens · Corredor D · Nível 2 · Posição 6'),
  ('ES01-D', 3, 1, 'ES-01 Estoque Seco Embalagens · Corredor D · Nível 3 · Posição 1'),
  ('ES01-D', 3, 2, 'ES-01 Estoque Seco Embalagens · Corredor D · Nível 3 · Posição 2'),
  ('ES01-D', 3, 3, 'ES-01 Estoque Seco Embalagens · Corredor D · Nível 3 · Posição 3'),
  ('ES01-D', 3, 4, 'ES-01 Estoque Seco Embalagens · Corredor D · Nível 3 · Posição 4'),
  ('ES01-D', 3, 5, 'ES-01 Estoque Seco Embalagens · Corredor D · Nível 3 · Posição 5'),
  ('ES01-D', 3, 6, 'ES-01 Estoque Seco Embalagens · Corredor D · Nível 3 · Posição 6'),
  ('ES01-D', 4, 1, 'ES-01 Estoque Seco Embalagens · Corredor D · Nível 4 · Posição 1'),
  ('ES01-D', 4, 2, 'ES-01 Estoque Seco Embalagens · Corredor D · Nível 4 · Posição 2'),
  ('ES01-D', 4, 3, 'ES-01 Estoque Seco Embalagens · Corredor D · Nível 4 · Posição 3'),
  ('ES01-D', 4, 4, 'ES-01 Estoque Seco Embalagens · Corredor D · Nível 4 · Posição 4'),
  ('ES01-D', 4, 5, 'ES-01 Estoque Seco Embalagens · Corredor D · Nível 4 · Posição 5'),
  ('ES01-D', 4, 6, 'ES-01 Estoque Seco Embalagens · Corredor D · Nível 4 · Posição 6'),
  ('ES02-A', 1, 1, 'ES-02 Estoque Seco Insumos · Corredor A · Nível 1 · Posição 1'),
  ('ES02-A', 1, 2, 'ES-02 Estoque Seco Insumos · Corredor A · Nível 1 · Posição 2'),
  ('ES02-A', 1, 3, 'ES-02 Estoque Seco Insumos · Corredor A · Nível 1 · Posição 3'),
  ('ES02-A', 1, 4, 'ES-02 Estoque Seco Insumos · Corredor A · Nível 1 · Posição 4'),
  ('ES02-A', 1, 5, 'ES-02 Estoque Seco Insumos · Corredor A · Nível 1 · Posição 5'),
  ('ES02-A', 1, 6, 'ES-02 Estoque Seco Insumos · Corredor A · Nível 1 · Posição 6'),
  ('ES02-A', 2, 1, 'ES-02 Estoque Seco Insumos · Corredor A · Nível 2 · Posição 1'),
  ('ES02-A', 2, 2, 'ES-02 Estoque Seco Insumos · Corredor A · Nível 2 · Posição 2'),
  ('ES02-A', 2, 3, 'ES-02 Estoque Seco Insumos · Corredor A · Nível 2 · Posição 3'),
  ('ES02-A', 2, 4, 'ES-02 Estoque Seco Insumos · Corredor A · Nível 2 · Posição 4'),
  ('ES02-A', 2, 5, 'ES-02 Estoque Seco Insumos · Corredor A · Nível 2 · Posição 5'),
  ('ES02-A', 2, 6, 'ES-02 Estoque Seco Insumos · Corredor A · Nível 2 · Posição 6'),
  ('ES02-A', 3, 1, 'ES-02 Estoque Seco Insumos · Corredor A · Nível 3 · Posição 1'),
  ('ES02-A', 3, 2, 'ES-02 Estoque Seco Insumos · Corredor A · Nível 3 · Posição 2'),
  ('ES02-A', 3, 3, 'ES-02 Estoque Seco Insumos · Corredor A · Nível 3 · Posição 3'),
  ('ES02-A', 3, 4, 'ES-02 Estoque Seco Insumos · Corredor A · Nível 3 · Posição 4'),
  ('ES02-A', 3, 5, 'ES-02 Estoque Seco Insumos · Corredor A · Nível 3 · Posição 5'),
  ('ES02-A', 3, 6, 'ES-02 Estoque Seco Insumos · Corredor A · Nível 3 · Posição 6'),
  ('ES02-A', 4, 1, 'ES-02 Estoque Seco Insumos · Corredor A · Nível 4 · Posição 1'),
  ('ES02-A', 4, 2, 'ES-02 Estoque Seco Insumos · Corredor A · Nível 4 · Posição 2'),
  ('ES02-A', 4, 3, 'ES-02 Estoque Seco Insumos · Corredor A · Nível 4 · Posição 3'),
  ('ES02-A', 4, 4, 'ES-02 Estoque Seco Insumos · Corredor A · Nível 4 · Posição 4'),
  ('ES02-A', 4, 5, 'ES-02 Estoque Seco Insumos · Corredor A · Nível 4 · Posição 5'),
  ('ES02-A', 4, 6, 'ES-02 Estoque Seco Insumos · Corredor A · Nível 4 · Posição 6'),
  ('ES02-B', 1, 1, 'ES-02 Estoque Seco Insumos · Corredor B · Nível 1 · Posição 1'),
  ('ES02-B', 1, 2, 'ES-02 Estoque Seco Insumos · Corredor B · Nível 1 · Posição 2'),
  ('ES02-B', 1, 3, 'ES-02 Estoque Seco Insumos · Corredor B · Nível 1 · Posição 3'),
  ('ES02-B', 1, 4, 'ES-02 Estoque Seco Insumos · Corredor B · Nível 1 · Posição 4'),
  ('ES02-B', 1, 5, 'ES-02 Estoque Seco Insumos · Corredor B · Nível 1 · Posição 5'),
  ('ES02-B', 1, 6, 'ES-02 Estoque Seco Insumos · Corredor B · Nível 1 · Posição 6'),
  ('ES02-B', 2, 1, 'ES-02 Estoque Seco Insumos · Corredor B · Nível 2 · Posição 1'),
  ('ES02-B', 2, 2, 'ES-02 Estoque Seco Insumos · Corredor B · Nível 2 · Posição 2'),
  ('ES02-B', 2, 3, 'ES-02 Estoque Seco Insumos · Corredor B · Nível 2 · Posição 3'),
  ('ES02-B', 2, 4, 'ES-02 Estoque Seco Insumos · Corredor B · Nível 2 · Posição 4'),
  ('ES02-B', 2, 5, 'ES-02 Estoque Seco Insumos · Corredor B · Nível 2 · Posição 5'),
  ('ES02-B', 2, 6, 'ES-02 Estoque Seco Insumos · Corredor B · Nível 2 · Posição 6'),
  ('ES02-B', 3, 1, 'ES-02 Estoque Seco Insumos · Corredor B · Nível 3 · Posição 1'),
  ('ES02-B', 3, 2, 'ES-02 Estoque Seco Insumos · Corredor B · Nível 3 · Posição 2'),
  ('ES02-B', 3, 3, 'ES-02 Estoque Seco Insumos · Corredor B · Nível 3 · Posição 3'),
  ('ES02-B', 3, 4, 'ES-02 Estoque Seco Insumos · Corredor B · Nível 3 · Posição 4'),
  ('ES02-B', 3, 5, 'ES-02 Estoque Seco Insumos · Corredor B · Nível 3 · Posição 5'),
  ('ES02-B', 3, 6, 'ES-02 Estoque Seco Insumos · Corredor B · Nível 3 · Posição 6'),
  ('ES02-B', 4, 1, 'ES-02 Estoque Seco Insumos · Corredor B · Nível 4 · Posição 1'),
  ('ES02-B', 4, 2, 'ES-02 Estoque Seco Insumos · Corredor B · Nível 4 · Posição 2'),
  ('ES02-B', 4, 3, 'ES-02 Estoque Seco Insumos · Corredor B · Nível 4 · Posição 3'),
  ('ES02-B', 4, 4, 'ES-02 Estoque Seco Insumos · Corredor B · Nível 4 · Posição 4'),
  ('ES02-B', 4, 5, 'ES-02 Estoque Seco Insumos · Corredor B · Nível 4 · Posição 5'),
  ('ES02-B', 4, 6, 'ES-02 Estoque Seco Insumos · Corredor B · Nível 4 · Posição 6'),
  ('ES02-C', 1, 1, 'ES-02 Estoque Seco Insumos · Corredor C · Nível 1 · Posição 1'),
  ('ES02-C', 1, 2, 'ES-02 Estoque Seco Insumos · Corredor C · Nível 1 · Posição 2'),
  ('ES02-C', 1, 3, 'ES-02 Estoque Seco Insumos · Corredor C · Nível 1 · Posição 3'),
  ('ES02-C', 1, 4, 'ES-02 Estoque Seco Insumos · Corredor C · Nível 1 · Posição 4'),
  ('ES02-C', 1, 5, 'ES-02 Estoque Seco Insumos · Corredor C · Nível 1 · Posição 5'),
  ('ES02-C', 1, 6, 'ES-02 Estoque Seco Insumos · Corredor C · Nível 1 · Posição 6'),
  ('ES02-C', 2, 1, 'ES-02 Estoque Seco Insumos · Corredor C · Nível 2 · Posição 1'),
  ('ES02-C', 2, 2, 'ES-02 Estoque Seco Insumos · Corredor C · Nível 2 · Posição 2'),
  ('ES02-C', 2, 3, 'ES-02 Estoque Seco Insumos · Corredor C · Nível 2 · Posição 3'),
  ('ES02-C', 2, 4, 'ES-02 Estoque Seco Insumos · Corredor C · Nível 2 · Posição 4'),
  ('ES02-C', 2, 5, 'ES-02 Estoque Seco Insumos · Corredor C · Nível 2 · Posição 5'),
  ('ES02-C', 2, 6, 'ES-02 Estoque Seco Insumos · Corredor C · Nível 2 · Posição 6'),
  ('ES02-C', 3, 1, 'ES-02 Estoque Seco Insumos · Corredor C · Nível 3 · Posição 1'),
  ('ES02-C', 3, 2, 'ES-02 Estoque Seco Insumos · Corredor C · Nível 3 · Posição 2'),
  ('ES02-C', 3, 3, 'ES-02 Estoque Seco Insumos · Corredor C · Nível 3 · Posição 3'),
  ('ES02-C', 3, 4, 'ES-02 Estoque Seco Insumos · Corredor C · Nível 3 · Posição 4'),
  ('ES02-C', 3, 5, 'ES-02 Estoque Seco Insumos · Corredor C · Nível 3 · Posição 5'),
  ('ES02-C', 3, 6, 'ES-02 Estoque Seco Insumos · Corredor C · Nível 3 · Posição 6'),
  ('ES02-C', 4, 1, 'ES-02 Estoque Seco Insumos · Corredor C · Nível 4 · Posição 1'),
  ('ES02-C', 4, 2, 'ES-02 Estoque Seco Insumos · Corredor C · Nível 4 · Posição 2'),
  ('ES02-C', 4, 3, 'ES-02 Estoque Seco Insumos · Corredor C · Nível 4 · Posição 3'),
  ('ES02-C', 4, 4, 'ES-02 Estoque Seco Insumos · Corredor C · Nível 4 · Posição 4'),
  ('ES02-C', 4, 5, 'ES-02 Estoque Seco Insumos · Corredor C · Nível 4 · Posição 5'),
  ('ES02-C', 4, 6, 'ES-02 Estoque Seco Insumos · Corredor C · Nível 4 · Posição 6'),
  ('ES02-D', 1, 1, 'ES-02 Estoque Seco Insumos · Corredor D · Nível 1 · Posição 1'),
  ('ES02-D', 1, 2, 'ES-02 Estoque Seco Insumos · Corredor D · Nível 1 · Posição 2'),
  ('ES02-D', 1, 3, 'ES-02 Estoque Seco Insumos · Corredor D · Nível 1 · Posição 3'),
  ('ES02-D', 1, 4, 'ES-02 Estoque Seco Insumos · Corredor D · Nível 1 · Posição 4'),
  ('ES02-D', 1, 5, 'ES-02 Estoque Seco Insumos · Corredor D · Nível 1 · Posição 5'),
  ('ES02-D', 1, 6, 'ES-02 Estoque Seco Insumos · Corredor D · Nível 1 · Posição 6'),
  ('ES02-D', 2, 1, 'ES-02 Estoque Seco Insumos · Corredor D · Nível 2 · Posição 1'),
  ('ES02-D', 2, 2, 'ES-02 Estoque Seco Insumos · Corredor D · Nível 2 · Posição 2'),
  ('ES02-D', 2, 3, 'ES-02 Estoque Seco Insumos · Corredor D · Nível 2 · Posição 3'),
  ('ES02-D', 2, 4, 'ES-02 Estoque Seco Insumos · Corredor D · Nível 2 · Posição 4'),
  ('ES02-D', 2, 5, 'ES-02 Estoque Seco Insumos · Corredor D · Nível 2 · Posição 5'),
  ('ES02-D', 2, 6, 'ES-02 Estoque Seco Insumos · Corredor D · Nível 2 · Posição 6'),
  ('ES02-D', 3, 1, 'ES-02 Estoque Seco Insumos · Corredor D · Nível 3 · Posição 1'),
  ('ES02-D', 3, 2, 'ES-02 Estoque Seco Insumos · Corredor D · Nível 3 · Posição 2'),
  ('ES02-D', 3, 3, 'ES-02 Estoque Seco Insumos · Corredor D · Nível 3 · Posição 3'),
  ('ES02-D', 3, 4, 'ES-02 Estoque Seco Insumos · Corredor D · Nível 3 · Posição 4'),
  ('ES02-D', 3, 5, 'ES-02 Estoque Seco Insumos · Corredor D · Nível 3 · Posição 5'),
  ('ES02-D', 3, 6, 'ES-02 Estoque Seco Insumos · Corredor D · Nível 3 · Posição 6'),
  ('ES02-D', 4, 1, 'ES-02 Estoque Seco Insumos · Corredor D · Nível 4 · Posição 1'),
  ('ES02-D', 4, 2, 'ES-02 Estoque Seco Insumos · Corredor D · Nível 4 · Posição 2'),
  ('ES02-D', 4, 3, 'ES-02 Estoque Seco Insumos · Corredor D · Nível 4 · Posição 3'),
  ('ES02-D', 4, 4, 'ES-02 Estoque Seco Insumos · Corredor D · Nível 4 · Posição 4'),
  ('ES02-D', 4, 5, 'ES-02 Estoque Seco Insumos · Corredor D · Nível 4 · Posição 5'),
  ('ES02-D', 4, 6, 'ES-02 Estoque Seco Insumos · Corredor D · Nível 4 · Posição 6');

-- 8 usuários Arte Trigo (senha padrão: Admin@1234)
-- Admins: Gerente de Logística + Supervisora de Qualidade
-- Operadores: câmara fria ×2, conferente, separador, expedição ×2
INSERT INTO usuario (nome, email, senha_hash, perfil, ativo) VALUES
  ('Carlos Eduardo Matos', 'carlos.matos@artetrigo.com.br', '$2b$12$CU2ggnSrYAxMd6z/WcmqYechRweErRaj41tmy0pqCbJeDPK1U.18y', 'administrador', 1),
  ('Fernanda Lima', 'fernanda.lima@artetrigo.com.br', '$2b$12$CU2ggnSrYAxMd6z/WcmqYechRweErRaj41tmy0pqCbJeDPK1U.18y', 'administrador', 1),
  ('José Carlos Oliveira', 'jose.oliveira@artetrigo.com.br', '$2b$12$CU2ggnSrYAxMd6z/WcmqYechRweErRaj41tmy0pqCbJeDPK1U.18y', 'operador', 1),
  ('Patrícia Souza', 'patricia.souza@artetrigo.com.br', '$2b$12$CU2ggnSrYAxMd6z/WcmqYechRweErRaj41tmy0pqCbJeDPK1U.18y', 'operador', 1),
  ('Marcos Antônio Silva', 'marcos.silva@artetrigo.com.br', '$2b$12$CU2ggnSrYAxMd6z/WcmqYechRweErRaj41tmy0pqCbJeDPK1U.18y', 'operador', 1),
  ('Ana Beatriz Santos', 'ana.santos@artetrigo.com.br', '$2b$12$CU2ggnSrYAxMd6z/WcmqYechRweErRaj41tmy0pqCbJeDPK1U.18y', 'operador', 1),
  ('Ricardo Mendes', 'ricardo.mendes@artetrigo.com.br', '$2b$12$CU2ggnSrYAxMd6z/WcmqYechRweErRaj41tmy0pqCbJeDPK1U.18y', 'operador', 1),
  ('Tatiane Ferreira', 'tatiane.ferreira@artetrigo.com.br', '$2b$12$CU2ggnSrYAxMd6z/WcmqYechRweErRaj41tmy0pqCbJeDPK1U.18y', 'operador', 1);

-- 22 produtos Arte Trigo (4 categorias)
INSERT INTO produto (nome, categoria, unidade_medida, estoque_minimo, ativo) VALUES
  ('Pão Francês', 'Pães', 'unidade', 50, 1),
  ('Pão de Forma Tradicional', 'Pães', 'pacote', 50, 1),
  ('Pão de Queijo GG', 'Pães', 'unidade', 50, 1),
  ('Pão Sírio', 'Pães', 'pacote', 50, 1),
  ('Pão Integral', 'Pães', 'pacote', 50, 1),
  ('Pão de Hambúrguer', 'Pães', 'unidade', 50, 1),
  ('Coxinha de Frango', 'Salgados', 'unidade', 30, 1),
  ('Esfirra de Carne', 'Salgados', 'unidade', 30, 1),
  ('Pastel de Queijo', 'Salgados', 'unidade', 30, 1),
  ('Croissant Presunto/Queijo', 'Salgados', 'unidade', 30, 1),
  ('Enroladinho de Salsicha', 'Salgados', 'unidade', 30, 1),
  ('Pão de Mel', 'Quitandas', 'unidade', 20, 1),
  ('Biscoito Amanteigado', 'Quitandas', 'pacote', 20, 1),
  ('Rosca de Coco', 'Quitandas', 'unidade', 20, 1),
  ('Bolo de Cenoura Fatia', 'Quitandas', 'fatia', 20, 1),
  ('Brownie de Chocolate', 'Quitandas', 'unidade', 20, 1),
  ('Farinha de Trigo 25kg', 'Insumos', 'saco', 10, 1),
  ('Fermento Biológico 500g', 'Insumos', 'pacote', 10, 1),
  ('Açúcar Refinado 5kg', 'Insumos', 'pacote', 10, 1),
  ('Manteiga 500g', 'Insumos', 'pacote', 10, 1),
  ('Leite Integral 1L', 'Insumos', 'unidade', 10, 1),
  ('Ovos (caixa 30un)', 'Insumos', 'caixa', 10, 1);


-- ================================================================
-- ETAPA 3 — Lotes Arte Trigo
-- ================================================================
INSERT INTO lote (numero_lote, id_produto, data_fabricacao, data_validade, quantidade, id_localizacao, status_lote, motivo_bloqueio, data_bloqueio) VALUES
  ('LOT-AT-001',  1, '2026-05-27', '2026-05-29',  200, 1,   'ativo',     NULL,                          NULL),
  ('LOT-AT-002',  7, '2026-05-27', '2026-05-30',  150, 97,  'ativo',     NULL,                          NULL),
  ('LOT-AT-003', 17, '2026-04-27', '2026-10-27',   40, 385, 'ativo',     NULL,                          NULL),
  ('LOT-AT-004', 12, '2026-05-26', '2026-06-06',   80, 481, 'ativo',     NULL,                          NULL),
  ('LOT-AT-005', 18, '2026-05-07', '2026-05-28',   15, 193, 'ativo',     NULL,                          NULL),
  ('LOT-AT-006', 13, '2026-05-26', '2026-06-15',   30, 289, 'bloqueado', 'Suspeita de contaminação', '2026-05-26 10:00:00');

-- ================================================================
-- ETAPA 3 — Movimentações Arte Trigo (~20 registros, últimos 7 dias)
-- Ordem: id_lote segue a sequência dos INSERTs acima (1=LOT-AT-001 … 6=LOT-AT-006)
-- ================================================================
INSERT INTO movimentacao (tipo, data_movimentacao, quantidade, id_lote, id_usuario, id_localizacao_origem, id_localizacao_destino, motivo_movimentacao, observacao, status) VALUES
  -- 2026-05-27 (hoje)
  ('entrada',       '2026-05-27 06:30:00', 200, 1, 1, NULL, 1,   'Produção matinal', 'Pão Francês · turno A',         'concluida'),
  ('saida',         '2026-05-27 09:15:00',  45, 1, 2, 1,    NULL, 'Venda balcão',    'Loja própria · 45 unidades',    'concluida'),
  ('entrada',       '2026-05-27 10:00:00', 150, 2, 1, NULL, 97,  'Produção matinal', 'Coxinha de Frango · turno A',   'concluida'),
  ('saida',         '2026-05-27 11:30:00',  60, 2, 2, 97,   NULL, 'Venda atacado',   'Pedido #AT-4812',               'concluida'),
  -- 2026-05-26 (ontem)
  ('entrada',       '2026-05-26 06:15:00',  80, 4, 4, NULL, 481, 'Produção diária',  'Pão de Mel · turno A',          'concluida'),
  ('entrada',       '2026-05-26 07:00:00',  30, 6, 4, NULL, 289, 'Produção diária',  'Biscoito Amanteigado · turno A','concluida'),
  ('transferencia', '2026-05-26 14:10:00',  30, 6, 3, 289,  289, 'Reorganização CF04', 'Consolidação de posição',     'concluida'),
  ('ajuste',        '2026-05-26 15:45:00',   2, 5, 1, 193,  NULL, 'Embalagem danificada', 'Descarte controlado',      'concluida'),
  -- 2026-05-25
  ('saida',         '2026-05-25 07:00:00',   5, 3, 5, 385,  NULL, 'Uso produção',    'Farinha 25kg · turno A',        'concluida'),
  ('saida',         '2026-05-25 08:30:00',   3, 5, 6, 193,  NULL, 'Uso produção',    'Fermento 500g · turno A',       'concluida'),
  ('saida',         '2026-05-25 14:00:00',  20, 4, 2, 481,  NULL, 'Venda balcão',    'Pão de Mel · 20 unidades',      'concluida'),
  -- 2026-05-24
  ('saida',         '2026-05-24 09:30:00',   3, 5, 6, 193,  NULL, 'Uso produção',    'Fermento 500g · turno B',       'concluida'),
  ('saida',         '2026-05-24 10:00:00',   5, 3, 5, 385,  NULL, 'Uso produção',    'Farinha 25kg · turno B',        'concluida'),
  ('saida',         '2026-05-24 15:30:00',  35, 1, 2, 1,    NULL, 'Venda balcão',    'Loja própria · 35 unidades',    'concluida'),
  -- 2026-05-23
  ('saida',         '2026-05-23 08:00:00',   3, 5, 6, 193,  NULL, 'Uso produção',    'Fermento 500g · turno A',       'concluida'),
  ('saida',         '2026-05-23 09:00:00',   5, 3, 5, 385,  NULL, 'Uso produção',    'Farinha 25kg · turno A',        'concluida'),
  -- 2026-05-22
  ('saida',         '2026-05-22 09:00:00',   3, 5, 6, 193,  NULL, 'Uso produção',    'Fermento — estoque crítico',    'concluida'),
  ('saida',         '2026-05-22 10:00:00',   5, 3, 5, 385,  NULL, 'Uso produção',    'Farinha 25kg',                  'concluida'),
  -- 2026-05-21
  ('entrada',       '2026-05-21 08:00:00',  40, 3, 7, NULL, 385, 'Recebimento fornecedor', 'Moinho Sul · NF-4521',    'concluida'),
  ('saida',         '2026-05-21 14:00:00',   5, 3, 5, 385,  NULL, 'Uso produção',    'Farinha 25kg · turno A',        'concluida');

-- =============================================================
-- VALIDAÇÃO FINAL
-- =============================================================

SHOW TABLES;
SHOW TRIGGERS;
SELECT id, nome, email, perfil, ativo FROM usuario;